version: "3.8"
services:
  backend:
    build:
      context: ./backend
    image: localhost/augmented-backend:latest
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./front
    image: localhost/fs-frontend-image:latest
    ports:
      - "4200:80"
    volumes:
      - .:/workspace:cached
    tty: true
    stdin_open: true
